# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.product:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Product" ]
        tags:      [ { name: "api.resource" } ]
    resource.user:
        parent:    "api.resource"
        arguments: [ "AppBundle\\UserBundle\\Entity\\User" ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "user_read" ] } ]
            -      method:    "initDenormalizationContext"
                   arguments: [ { groups: [ "user_write" ] } ]
        tags:      [ { name: "api.resource" } ]
